#! /usr/bin/bash

#  Para darle color a las respuetas
#rojo='\e[0;31m'; rojof='\e[0m'
#amarillo='\e[1;33m'; amarillof='\e[0m'
#azul='\e[0;34m'; azulf='\e[0m'
#	echo -e $azul



##############################################
# es para  que paty tenga voz
altavoz="espeak -ves-la -p 99"

# esta es una funcion para la lista de preguntas
# en si solo coje las lineas que empiezan por "
# en este caso son las preguntas, si ubiera otro case,
# tambien las presentaria
lista_de_preguntas(){
#	echo -e "$azul Esta es la  lista de preguntas que puedo responder"
	echo ===================================
	sed -n '/^"/p' /usr/local/bin/paty | nl
	echo ===================================
#	echo -e $azulf
}



# esto es para hacer un bucle infinito para cuando llame a paty 
# y salir de el solo cuando diga
# paty chao, o algo parecido 

#while [ -z $respuesta ]  || [ $respuesta != 'si'  ] 
#do
#        read -p '>> ' respuesta
#done


# con esto cojo los parametros enviados para concatenarlos y hacer la pregunta
# a causa de esto hay un espacio al final de cada pregunta (a correjir)
# que me obliga a tenerlo en cuenta dentro del 'case'
for i in "$@"
do
  	pregunta+="$i "
done



#- Preguntas Sistema ----------------------------------
case "$pregunta" in 

"actualizate ")

	path="/usr/local/bin/"

	r="Solo puedes pedirme eso si eres amigo del 'Administrador'" 
	echo $r | $altavoz


	echo El path es: $path
	echo 
	diff ~/paty/hola $path 
	sudo cp paty $path
;;

"dame la lista de programas ")
	echo Voy a buscarlos dame un segundo porfavor: | $altavoz
	rpm -qa | nl
	echo Aqui tienes los programas que encontre | $altavoz
	echo 
;;

# para que funcion esto debo aun definir su formato 
"dame detalle de ")
       rpm -qai "$2"
;;

"que version de fedora estoy usando ")
##	sudo dnf install -y redhat-lsb-core
	echo 
	lsb_release -a
	cat /etc/redhat-release	
	echo 
;;

"cuales son los grupos de paquetes disponibles ")
	echo Voy a buscarlos dame un segundo porfavor: | $altavoz
	sudo dnf grouplist
	echo Aqui tienes los programas que encontre | $altavoz

;;

"actualiza el sistema ")
	echo | espeak "Yes sr."
	sudo dnf -y update
	echo Ahora limpieza de paquetes
	dnf clean packages
	echo Listo $USER . 
;;

"dame los usuarios del sistema ")
	echo cat /etc/passwd | nl
	cat /etc/passwd | nl
;;


"cuales son las ip de mis cartas ")
	ifconfig | grep inet
;;


"32 o 64 ")
	echo Tu compu es: `arch`
	r="Aca tienes mas detalles"
	echo $r | $altavoz
	lscpu
	echo 
	lshw -class cpu
;;

"abre un editor de texto ")
	r="A sus ordenes"
	echo $r | $altavoz
	gedit 
;;

"cual es la version de apache ")
	echo httpd -v
	httpd -v
;;

"muestrame los procesos del sistema ")
	echo ps axjf
	ps axjf
;;


"quien esta conectado ")
	r="Dejame ver"
	echo $r | $altavoz
	who
;;

"quien soy ")
	r="Tu eres `whoami` lo has olvidado?"
	echo $r | $altavoz
;; 


"que fecha es ")
	date
;;


#- Preguntas personales ---------------------------------------------------
"hola ")
	
	r="Hola $USER me da gusto saber de ti!"
	echo $r | $altavoz
;;

"chao ")
	r="Te voy a extrañar mucho, hasta pronto"
	echo $r | $altavoz
;;

"como te llamas "  | "cual es tu nombre ")
	r="Mi nombre es Patricia, pero puedes decirme paty"
	echo $r | $altavoz
;;

"que edad tienes " | "cuantos años tienes ")
	r="Tengo 18" 
	echo $r | $altavoz
;;

"donde vives ")
	r="En realidad no vivo, solo soy un programa de computador te invito que veas mi sitio web"
	echo $r | $altavoz	
	firefox https://github.com/robincoello/paty
;;

"como me llamo ")
	r=$USER
	echo $r | $altavoz
;;

#- Ayuda de paty
"ayudame " | "ayuda")
	echo AYUDA
	r="Ya ya pero no llores!"
	echo $r | $altavoz
	lista_de_preguntas
;;

#- Otras ----------------------------------------------------------
"me quieres ")
	r="Claro que si, te adoro"
	echo $r | $altavoz
;;

"donde estas ")
	r="Aqui en el mismo lugar, con la misma gente, para que tu al volver no sientas nada extraño"
	echo $r | $altavoz
;;

"quiero ser tu amigo ")
	if [ -f "~/.paty/$USER/datos/nacio_en" ]; then
		echo ya lo somos
	fi
	# creamos una carpeta escondida con el nombre de .paty
	# dentro de ella guardaremos datos personales del $USER
	# para personalizar las respuestas
	mkdir ~/.paty
	echo Ohhhh, listo $USER ahora lo somos 
	$altavoz "PERO SOLO SI ERES SOLTERO"
	echo Donde naciste?
	mkdir -p ~/.paty/$USER/datos
	read l
	# registramos su ciudad de nacimiento, 
	# creo que sera mejor hacerlo en un solo fichero 

	echo $l >  ~/.paty/$USER/datos/nacio_en
;;

"cuentame un chiste ")
	$altavoz -f "/home/$USER/.paty/chistes/1.txt"
	
;; 




#- Preguntas no existentes --------------------------------------
*)
# si el usuario pregunta algo que no esta revisto, 
# le pasamos un mensaje
	r="$USER, tienes que hacer una pregunta que pueda responder"
	echo $r | $altavoz
# y la lista de preguntas que podemos responder
	lista_de_preguntas

;;

esac

#	echo -e $azulf
